# Generated by Django 2.1.1 on 2018-10-03 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_production', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete='PROTECT', related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete='PROTECT', related_name='bu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ip', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('INUSE', 'INUSE'), ('SPARE', 'SPARE'), ('LEGACY', 'LEGACY'), ('SHUTDOWN', 'SHUTDOWN')], default='SPARE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete='PROTECT', related_name='host', to='cmdb.Application', to_field='name')),
                ('owner', models.ForeignKey(default=1, on_delete='PROTECT', related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bu', models.ForeignKey(default='', on_delete='PROTECT', related_name='product', to='cmdb.Bu', to_field='name')),
                ('owner', models.ForeignKey(default=1, on_delete='PROTECT', related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(default='', on_delete='PROTECT', related_name='application', to='cmdb.Product', to_field='name'),
        ),
    ]
