# Generated by Django 2.1.1 on 2018-10-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ip', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('INUSE', 'INUSE'), ('SPARE', 'SPARE'), ('LEGACY', 'LEGACY'), ('SHUTDOWN', 'SHUTDOWN')], default='SPARE', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('bu', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='host',
            name='application',
            field=models.ForeignKey(on_delete='PROTECT', to='cmdb.Application', to_field='name'),
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(default='unknown', on_delete='PROTECT', to='cmdb.Product', to_field='name'),
        ),
    ]
