# Generated by Django 2.1.1 on 2018-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20181001_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.ForeignKey(default='', on_delete='PROTECT', to='cmdb.Product'),
        ),
        migrations.AlterField(
            model_name='host',
            name='application',
            field=models.ForeignKey(on_delete='PROTECT', to='cmdb.Application'),
        ),
    ]
