# Generated by Django 2.1.1 on 2018-10-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20181001_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bu',
            field=models.ForeignKey(default='', on_delete='PROTECT', to='cmdb.Bu'),
        ),
    ]
