# Generated by Django 2.1.1 on 2018-10-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20181001_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.ForeignKey(default='', on_delete='PROTECT', to='cmdb.Product', to_field='name'),
        ),
    ]
