# Generated by Django 2.1.1 on 2018-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20181001_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='application',
            field=models.ForeignKey(on_delete='PROTECT', to='cmdb.Application', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bu',
            field=models.ForeignKey(default='', on_delete='PROTECT', to='cmdb.Bu', to_field='name'),
        ),
    ]
