# Generated by Django 2.1.1 on 2018-10-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20181002_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.ForeignKey(default='', on_delete='PROTECT', to='cmdb.Product', to_field='name'),
        ),
        migrations.AlterField(
            model_name='host',
            name='application',
            field=models.ForeignKey(on_delete='PROTECT', to='cmdb.Application', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bu',
            field=models.ForeignKey(default='', on_delete='PROTECT', to='cmdb.Bu', to_field='name'),
        ),
    ]
